### PR TITLE
feat: notebook layout

### PR DESCRIPTION
**Pull request by jravenel**
Are you ok with the outline of my notebook?

### CODE REVIEW

**Comment by jravenel** [comment]
@FlorentLvr I think you committed on my branch 😅😅😅

**Comment by abrahamalen** [comment]
@FlorentLvr review pending

**Comment by jravenel** [comment]
@FlorentLvr the notebook is 95% ready to review in term of layout and responsiveness. The 5% missing items are:
- the fact to have the dropdown with decent width → this maybe you can check but don't bother too much right now, we can fix later
- the fact to have the 3 graphs per row vs my initial idea → I think it's ok to start with 2x2 for now. keeping things simple to move forward.

Could you please review the notebook and let me know?

Here is a small GIF to show how it looks like:
Aug-15-2022 17-26-05


cc @abrahamalen, I saw you mentioned review pending but until there is a real call to action from the member to ask for review, it's not really a review. We are still in the process of committing to the branch until it's almost done. Feel free to check.

**Comment by jravenel** [comment]
@eliasdabbas thanks for the help this morning, the style tag was responsible for the problem.

**Comment by FlorentLvr** [comment]
> @FlorentLvr the notebook is 95% ready to review in term of layout and responsiveness. The 5% missing items are:
> 
> * the fact to have the dropdown with decent width → this maybe you can check but don't bother too much right now, we can fix later
> * the fact to have the 3 graphs per row vs my initial idea → I think it's ok to start with 2x2 for now. keeping things simple to move forward.
> 
> Could you please review the notebook and let me know?
> 
> Here is a small GIF to show how it looks like: Aug-15-2022 17-26-05 [ Aug-15-2022 17-26-05 ](https://user-images.githubusercontent.com/21052349/184664936-8a0e608a-9340-4747-bd71-7ac064f675f1.gif) [ ](https://user-images.githubusercontent.com/21052349/184664936-8a0e608a-9340-4747-bd71-7ac064f675f1.gif)
> 
> cc @abrahamalen, I saw you mentioned review pending but until there is a real call to action from the member to ask for review, it's not really a review. We are still in the process of committing to the branch until it's almost done. Feel free to check.

@jravenel, I will have a look right now :)

**Comment by FlorentLvr** [comment]
@jravenel, just review and it's OK for me. I made some changes as commented on my commit.

**Pull request merged**
