### PR TITLE
feat: General layout 

### PR DESCRIPTION
**Pull request by Samael71**
Hi just finished this can someone check it out?

### CODE REVIEW

**Comment by FlorentLvr** [comment]
@Samael71 , it's all good. Just made a few changes on your notebook.

**Comment by jravenel** [comment]
@Samael71 I will try to review it today, don't forget to ping me in comment to make sure I know i have to review.

**Comment by Samael71** [comment]
The dashboard is done. Styling ad functionality. @jravenel Can you or @FlorentLvr review it for merging?

**Comment by FlorentLvr** [comment]
> The dashboard is done. Styling ad functionality. @jravenel Can you or @FlorentLvr review it for merging?

@Samael71 , thank you for your work! It's working well. I made some modifications and noticed some error. Please see my comments below.

**Comment by FlorentLvr** [comment]
When I add new data in your dataset, the conditional formatting are not working anymore >
image

**Comment by FlorentLvr** [comment]
Rows are not displayed in the same order as specifications:
image

image

**Comment by FlorentLvr** [comment]
When I select a platform, I expected to have only 1 table displayed =>

image

**Comment by Samael71** [comment]
@FlorentLvr The issues mentioned above were all fixed. Can you review it again?

**Pull request merged**
